### PR TITLE
feat: add `unproject_layout` support

### PR DESCRIPTION
**Pull request by agoose77**
This PR will add support for dask-contrib/dask-awkward#184 to the uproot input layer, so that unused fields can still be partially represented in the layouts of the loaded arrays.

### CODE REVIEW

**Comment by douglasdavis** [comment]
at @agoose77 I opened #901 which is based on the branch in this PR; I think I covered all 4 cases (the 2 callable classes and also the 2 possible full forms- the remapped one or the raw one)

**Comment by lgray** [comment]
do we need a fairly immediate uproot 5.0.10?

**Comment by douglasdavis** [comment]
If this is working I would think it warrants a release. But I just tested the branch on @iasonkrom's example:

```python
from coffea.nanoevents import NanoAODSchema, NanoEventsFactory
import os

fname = "coffea/tests/samples/nano_dy.root"
events = NanoEventsFactory.from_root(
    {os.path.abspath(fname): "Events"},
    schemaclass=NanoAODSchema,
    metadata={"dataset": "DYJets"},
    permit_dask=True,
).events()

print(len(events.Electron))
```

And we have a problem in either in unproject_layout or in the way we're calling it here in uproot. I haven't dug into this yet.


```python
>>> from coffea.nanoevents import NanoAODSchema, NanoEventsFactory
>>> import os
>>> 
>>> fname = "coffea/tests/samples/nano_dy.root"
>>> events = NanoEventsFactory.from_root(
...     {os.path.abspath(fname): "Events"},
...     schemaclass=NanoAODSchema,
...     metadata={"dataset": "DYJets"},
...     permit_dask=True,
... ).events()
/Users/ddavis/software/repos/coffea/src/coffea/nanoevents/schemas/nanoaod.py:215: RuntimeWarning: Missing cross-reference index for FatJet_genJetAK8Idx => GenJetAK8
  warnings.warn(
>>> 
>>> print(len(events.Electron))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask_awkward/lib/core.py", line 565, in __len__
    self.eager_compute_divisions()
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask_awkward/lib/core.py", line 1203, in eager_compute_divisions
    self._divisions = calculate_known_divisions(self)
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask_awkward/lib/core.py", line 1838, in calculate_known_divisions
    return (0, num.compute())
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/base.py", line 310, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/base.py", line 595, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/optimization.py", line 992, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ddavis/software/repos/uproot5/src/uproot/_dask.py", line 932, in __call__
    dask_awkward.lib.unproject_layout.unproject_layout(
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask_awkward/lib/unproject_layout.py", line 406, in unproject_layout
    return _unproject_layout(form, layout, layout.length, layout.backend)
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/dask_awkward/lib/unproject_layout.py", line 267, in _unproject_layout
    form.content(field),
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/awkward/forms/recordform.py", line 143, in content
    index = self.field_to_index(index_or_field)
  File "/Users/ddavis/.pyenv/versions/cafe/lib/python3.10/site-packages/awkward/forms/recordform.py", line 117, in field_to_index
    i = self._fields.index(field)
AttributeError: 'dict_keys' object has no attribute 'index'
```

**Comment by agoose77** [comment]
This is an Awkward bug that's fixed in #scikit-hep/awkward#2548!

**Comment by douglasdavis** [comment]
oh, awesome!

**Comment by douglasdavis** [comment]
and @iasonkrom's snippet now works :+1:

**Comment by jpivarski** [comment]
Is this done? More to the point, is it needed to fix a dask-awkward bug? I didn't get a notification about it because I wasn't pinged for review.

**Comment by lgray** [comment]
iiuc, at least for the downstream issues in nanoevents it depends on first the next awkward release?

**Comment by lgray** [comment]
though I don't see why we cannot merge it now (aside from perhaps a pinning issue, which may more appropriately be taken care of in coffea).

**Comment by jpivarski** [comment]
This PR can wait for the next Awkward release, which is coming up pretty soon anyway.

**Pull request merged**
