### PR TITLE
fix: change expected xz/lzma module location on cramjam

### PR DESCRIPTION
**Pull request by milesgranger**
I've [pre-released v2.8.3-rc1](https://pypi.org/project/cramjam/2.8.3rc1/#files), which has the XZ/LZMA stuff now as `cramjam.xz`. 
Would rather not break things for you, so until releasing `2.8.3`, I think this change, or something like it, should happen here or >= 2.8.3 will look like it doesn't have xz/lzma support.

xref https://github.com/milesgranger/cramjam/issues/126

### CODE REVIEW

**Comment by lgray** [comment]
Ah, sorry repeated you in #1167. I'll close that one.

@jpivarski @ioanaif this could use some attention.

**Review by jpivarski — COMMENTED** [review]
With this PR, we're effectively assuming that these are _all_ of the possible locations of `decompress` and `compress` functions:

* `cramjam.xz`
* `cramjam.experimental.lzma`
* not in cramjam; fallback to Python's builtin `lzma` module

So, for instance, there's no released version of cramjam with the following:

* `cramjam.lzma`
* `cramjam.experimental.xz`

Right?

Uproot's dependency on cramjam is `cramjam>=2.5.0`, so we have to check for all names in any released version of the package.

**Comment by jpivarski** [comment]
I just want to know about what names exist in all _released_ versions of cramjam. If there is already a released version in which it is named `cramjam.xz` and not `cramjam.lzma`, then Uproot is going to have to check both anyway. (Flexibility on the producer side isn't helpful, but flexibility on the consumer side is.)

**Comment by jpivarski** [comment]
<details>

```
% pip install 'cramjam==2.8.0'
Collecting cramjam==2.8.0
  Downloading cramjam-2.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Downloading cramjam-2.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 20.9 MB/s eta 0:00:00
Installing collected packages: cramjam
Successfully installed cramjam-2.8.0
% python
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cramjam
>>> cramjam.xz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cramjam' has no attribute 'xz'
>>> cramjam.lzma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cramjam' has no attribute 'lzma'
>>> cramjam.experimental
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cramjam' has no attribute 'experimental'
>>> import cramjam.experimental
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cramjam.experimental'
>>> 
% pip install 'cramjam==2.8.1'
Collecting cramjam==2.8.1
  Downloading cramjam-2.8.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Downloading cramjam-2.8.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 22.1 MB/s eta 0:00:00
Installing collected packages: cramjam
  Attempting uninstall: cramjam
    Found existing installation: cramjam 2.8.0
    Uninstalling cramjam-2.8.0:
      Successfully uninstalled cramjam-2.8.0
Successfully installed cramjam-2.8.1
% python
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cramjam
>>> cramjam.xz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cramjam' has no attribute 'xz'
>>> cramjam.lzma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cramjam' has no attribute 'lzma'
>>> cramjam.experimental
<module 'experimental'>
>>> cramjam.experimental.xz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'experimental' has no attribute 'xz'
>>> cramjam.experimental.lzma
<module 'lzma'>
>>> 
% pip install 'cramjam==2.8.2'
Collecting cramjam==2.8.2
  Downloading cramjam-2.8.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Downloading cramjam-2.8.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 21.4 MB/s eta 0:00:00
Installing collected packages: cramjam
  Attempting uninstall: cramjam
    Found existing installation: cramjam 2.8.1
    Uninstalling cramjam-2.8.1:
      Successfully uninstalled cramjam-2.8.1
Successfully installed cramjam-2.8.2
% python
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cramjam
>>> cramjam.xz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cramjam' has no attribute 'xz'
>>> cramjam.lzma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cramjam' has no attribute 'lzma'
>>> cramjam.experimental
<module 'experimental'>
>>> cramjam.experimental.xz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'experimental' has no attribute 'xz'
>>> cramjam.experimental.lzma
<module 'lzma'>
>>> 
% pip install 'cramjam==2.8.3-rc1'
Collecting cramjam==2.8.3-rc1
  Downloading cramjam-2.8.3rc1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Downloading cramjam-2.8.3rc1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 21.9 MB/s eta 0:00:00
Installing collected packages: cramjam
  Attempting uninstall: cramjam
    Found existing installation: cramjam 2.8.2
    Uninstalling cramjam-2.8.2:
      Successfully uninstalled cramjam-2.8.2
Successfully installed cramjam-2.8.3rc1
% python
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cramjam
>>> cramjam.xz
<module 'xz'>
>>> cramjam.lzma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cramjam' has no attribute 'lzma'
>>> cramjam.experimental
<module 'experimental'>
>>> cramjam.experimental.xz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'experimental' has no attribute 'xz'
>>> cramjam.experimental.lzma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'experimental' has no attribute 'lzma'
```

</details>

2.8.0
-----

* cramjam.xz: no
* cramjam.lzma: no
* cramjam.experimental: no

2.8.1
-----

* cramjam.xz: no
* cramjam.lzma: no
* cramjam.experimental.xz: no
* cramjam.experimental.lzma: yes

2.8.2
-----

* cramjam.xz: no
* cramjam.lzma: no
* cramjam.experimental.xz: no
* cramjam.experimental.lzma: yes

2.8.3-rc1
---------

* cramjam.xz: yes
* cramjam.lzma: no
* cramjam.experimental.xz: no
* cramjam.experimental.lzma: no

Conclusion
==========

Uproot can check for:

1. cramjam.xz
2. cramjam.experimental.lzma
3. Python's built-in lzma

in that order. That's what this PR does, so it's good.

**Comment by milesgranger** [comment]
Okay. I think maybe we're over complicating it. The previous implementation was at `cramjam.exerimental.lzma` now it'll be at `cramjam.xz`. At no point was it ever at `cramjam.lzma` or `cramjam.experimental.xz` so I'm a bit confused why that's part of this analysis? 

I'd also add the minor note that no checking order is needed between these two locations, unless there is some way to install two different versions of cramjam in the same environment; they're mutually exclusive, it'll be in one or the other.

**Comment by jpivarski** [comment]
@all-contributors please add @milesgranger for code

**Pull request merged**
