### PR TITLE
feat: use the v2 main release

### PR DESCRIPTION
**Pull request by agoose77**
This can't be merged until we have an `awkward==2.0.0rc0` out.

### CODE REVIEW

**Comment by agoose77** [comment]
Huh, I thought I'd installed pre-commit on this repo already. Oops!

**Comment by jpivarski** [comment]
I think this PR and #741 are both attempting to do the same thing. We both dropped the "`_v2`" everywhere, but I think our other commits differ.

**Comment by agoose77** [comment]
I think we can close this; I started work on dropping the v2 prefix, but I wasn't sure if the plan was to make uproot5 require `awkward >= 2.0`. :)

**Comment by jpivarski** [comment]
> I wasn't sure if the plan was to make uproot5 require `awkward >= 2.0`

It will require it. I probably need to make the pyproject.toml changes you made here in #741.

**Pull request closed without merging**
