### PR TITLE
fix: uproot was exposed in one place to dask's _task_spec overhaul

### PR DESCRIPTION
**Pull request by lgray**
c.f. https://github.com/dask-contrib/dask-awkward/pull/556

There don't appear to be any other places where uproot directly accesses dask innards.

### CODE REVIEW

**Comment by lgray** [comment]
@jpivarski please merge this as soon as it's all passing, we will need a timely release as well.

**Comment by lgray** [comment]
ah - of course this waits on the dask-awkward release first :-p

**Comment by pfackeldey** [comment]
@lgray there's no reason to increase the `dask-awkward` version requirement, or is there? The change checks for an update in dask for the new task_spec, but still handles the old case. (I think this PR is independent of the dask-awkward PR aswell in this sense)

**Comment by lgray** [comment]
And it's only for the dev extra as well, and since we check back to py39 we test all code paths.

**Review by jpivarski — APPROVED** [review]
I see that this follows upstream changes in Dask and has Uproot taking a new minimum dask-awkward version.

Looks good to me! I'll make a new release right after merging this PR.

**Pull request merged**
