### PR TITLE
refactor: prepare for Awkward 2.0.0rc1

### PR DESCRIPTION
**Pull request by jpivarski**
Starting by adapting to API changes and removing the "`_v2`" submodule.

### CODE REVIEW

**Comment by jpivarski** [comment]
c054c716f048a99ab0174ff90a1939068861c6c8 is the one thing that was in #736 but not this PR. Now this one can supercede it.

**Comment by agoose77** [comment]
@jpivarski oh, simple - we just need #742. I was just re-implementing that.

**Comment by agoose77** [comment]
I need to make one PR to be included in this RC. I'll link it here in the next couple of minutes

**Comment by jpivarski** [comment]
3d37ed74a9689e941222f6af950c627b75a6b33b installs Awkward from source to give this PR a fair test. (It's supposed to demonstrate testing against Awkward `main`.) That CI step, marked "TEMPORARY!" should be removed before this PR is done.

The 3.11 tests are failing because they can't find a suitable version of Awkward Array _before_ the latest wheel is replaced by the "TEMPORARY!" CI step. I think we can just ignore those.

**Pull request closed without merging**
