### PR TITLE
ci: Get test dependencies from one source

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Review by henryiii — APPROVED** [review]

**Comment by jpivarski** [comment]
Dropping flake8 on the reasoning that it's in pre-commit and doesn't need to be in `[test]`.

**Comment by jpivarski** [comment]
As soon as this passes, I'll merge it.

**Comment by henryiii** [comment]
I'll rebase my PRs after that, since this overlaps with them.

**Comment by jpivarski** [comment]
Observation: only "(ubuntu-latest, 3.8)" is running the ROOT tests, but that's okay. We only need one.

https://github.com/scikit-hep/uproot5/runs/8001891523?check_suite_focus=true

```
=========================== short test summary info ============================
SKIPPED [1] tests/test_0001-source-class.py:96: RECHECK: example.com is flaky, too
SKIPPED [1] tests/test_0001-source-class.py:135: RECHECK: example.com is flaky, too
SKIPPED [1] tests/test_0001-source-class.py:251: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0001-source-class.py:272: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0001-source-class.py:296: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0001-source-class.py:318: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0001-source-class.py:338: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0001-source-class.py:380: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0001-source-class.py:407: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0006-notify-when-downloaded.py:65: RECHECK: example.com is flaky, too
SKIPPED [1] tests/test_0006-notify-when-downloaded.py:81: RECHECK: example.com is flaky, too
SKIPPED [1] tests/test_0006-notify-when-downloaded.py:97: RECHECK: example.com is flaky, too
SKIPPED [1] tests/test_0006-notify-when-downloaded.py:147: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0006-notify-when-downloaded.py:169: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0006-notify-when-downloaded.py:191: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0007-single-chunk-interface.py:76: RECHECK: example.com is flaky, too
SKIPPED [1] tests/test_0007-single-chunk-interface.py:100: RECHECK: example.com is flaky, too
SKIPPED [1] tests/test_0007-single-chunk-interface.py:120: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0007-single-chunk-interface.py:141: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0007-single-chunk-interface.py:162: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0031-test-stl-containers.py:17: Implement non-memberwise std::map; we have a sample (map<string,double>)
SKIPPED [1] tests/test_0167-use-the-common-histogram-interface.py:134: Something's wrong with uproot-issue33.root and boost-histogram
SKIPPED [1] tests/test_0302-pickle.py:56: RECHECK: Run2012B_DoubleMuParked.root is super-flaky right now
SKIPPED [1] tests/test_0325-fix-windows-file-uris.py:10: Drive letters only parsed on Windows.
SKIPPED [1] tests/test_0416-writing-compressed-data.py:61: could not import 'zstandard': No module named 'zstandard'
SKIPPED [1] tests/test_0416-writing-compressed-data.py:150: could not import 'zstandard': No module named 'zstandard'
SKIPPED [1] tests/test_0416-writing-compressed-data.py:242: could not import 'zstandard': No module named 'zstandard'
SKIPPED [1] tests/test_0416-writing-compressed-data.py:336: could not import 'zstandard': No module named 'zstandard'
================== 554 passed, 28 skipped in 92.77s (0:01:32) ==================
```

**Comment by jpivarski** [comment]
Another observation: all/only the Linuxes test XRootD, and the only one that doesn't test `zstandard` decompression is the one that tests ROOT. Which may be because of some conda/pip overshadowing. But I guess that's okay, as `zstandard`-reading is tested elsewhere.

**Pull request merged**
