### PR TITLE
feat: refactoring the AwkwardForth code-discovery process

### PR DESCRIPTION
**Pull request by jpivarski**
tests/test_0637-setup-tests-for-AwkwardForth.py:

- [x] test_00
- [x] test_01
- [x] test_02
- [x] test_03
- [x] test_04
- [x] test_05
- [x] test_06
- [x] test_07
- [x] test_08
- [x] test_09
- [x] test_10
- [x] test_11
- [x] test_12
- [x] test_13
- [x] test_14
- [x] test_15
- [x] test_16
- [x] test_17
- [x] test_18
- [x] test_19
- [x] test_20
- [x] test_21
- [x] test_22
- [x] test_23
- [x] test_24
- [x] test_25
- [x] test_27
- [x] test_28
- [x] test_30
- [x] test_31
- [x] test_32
- [x] test_33
- [x] test_34
- [x] test_35
- [x] test_36
- [x] test_37
- [x] test_38
- [x] test_39
- [x] test_40
- [x] test_41
- [x] test_42
- [x] test_43
- [x] test_44
- [x] test_47
- [x] test_51
- [x] test_52
- [x] test_53
- [x] test_54
- [x] test_55
- [x] test_56
- [x] test_57
- [x] test_58
- [x] test_59
- [x] test_60
- [x] test_61
- [x] test_62
- [x] test_63
- [x] test_64
- [x] test_65
- [x] test_66
- [x] test_67
- [x] test_68
- [x] test_69
- [x] test_70
- [x] test_71
- [x] test_72
- [x] test_73
- [x] test_74
- [x] test_75
- [x] test_76
- [x] test_77
- [x] test_78
- [x] test_79
- [x] test_80
- [x] test_81

tests/test_0798_DAOD_PHYSLITE.py

- [x] test_AnalysisJetsAuxDyn_GhostTrack
- [x] test_TruthBosonAuxDyn_childLinks
- [x] test_TruthPhotonsAuxDyn_parentLinks
- [x] test_TruthTopAuxDyn_parentLinks

### CODE REVIEW

**Comment by jpivarski** [comment]
Things that will need to be done:

- [ ] append_code (and everything surrounding it) can be dropped
- [ ] remove old form generation
- [ ] replace ForthStashes with Nodes, sets name and model at construction
- [ ] remove ForthStash class
- [ ] `uproot._awkward_forth.forth_stash(context)` should instead be returning `forth_obj` (`ForthGenerator`), and therefore every `if forth_stash is not None` → `if forth_obj is not None`
- [ ] streamers cases
- [ ] hand-written Models like TObject (they're all in the models/ directory)
- [ ] AsArray?
- [ ] AsRVec?
- [ ] containers.py is probably done; there might be some cleaning up of dead code
- [ ] FIXMEs, like removing now-dead variables, such as `content` in streamers.py

**Comment by jpivarski** [comment]
Last batch of to-dos:

- [ ] AsRVec and AsSet are almost exactly like AsVector; rederive them from AsVector (by copy-paste and change)
- [ ] UnwindProtect context manager is detrimental; undo it
- [ ] Look over AsArray code; it has gotten messy
- [ ] Little things like `Forth_Generator` name; maybe import symbols into generated code in streamers.py to make it less verbose
- [ ] Merge `main` into this branch

Then it's done and should go into Uproot 5.2.0!

**Comment by jpivarski** [comment]
@SethBendigo, in case you're interested, stack push-pop is a relatively good replacement for UnwindProtect: 222759e13d0ab684d9bce4290c44159b4c644155. The cost is having to remember to pair up a `pop` with each `push`, but the benefit is that the code between the `push` and `pop` doesn't have to be duplicated, and we don't have to keep track of a `hold_previous_model` variable.

**Comment by jpivarski** [comment]
> Look over AsArray code; it has gotten messy

It's fine.

**Comment by jpivarski** [comment]
The test failures were failing in `main`, too: https://github.com/scikit-hep/uproot5/actions/runs/7074482533/job/19255559117

I manually triggered the tests on `main` to check that and forgot to follow up on it.

The test itself was literally saying that this should happen:

https://github.com/scikit-hep/uproot5/blob/cb36ef5ca789e5889ef967e2b6c4aea9c8a6d1e6/tests/test_0692_fsspec_writing.py#L133-L142

So I'll fix it now, in this PR, and it will carry through to `main` when I merge it.

**Comment by jpivarski** [comment]
@lobis, is 05ab1f3a2aa569645a508b73610961f722a1bc6f the right way to turn off the "waiting for fsspec/filesystem_spec#1426" error? If not, I'll fix it in this PR. It will enter `main` when this PR merges (maybe today).

**Comment by lobis** [comment]
> @lobis, is [05ab1f3](https://github.com/scikit-hep/uproot5/commit/05ab1f3a2aa569645a508b73610961f722a1bc6f) the right way to turn off the "waiting for [fsspec/filesystem_spec#1426](https://github.com/fsspec/filesystem_spec/pull/1426)" error? If not, I'll fix it in this PR. It will enter `main` when this PR merges (maybe today).

Yes, this is what was expected.

**Comment by jpivarski** [comment]
Well, @SethBendigo, it's done! It's finally and fully done. Thank you very much for all of your work on this!!!

When the tests pass one last time, I'll merge it.

**Comment by agoose77** [comment]
I didn't see that this got in!? How exciting @SethBendigo excellent work, this was a long one.

**Comment by SethBendigo** [comment]
Thanks @agoose77! Thanks @jpivarski, I really really appreciated your help throughout. I had a lot of fun and learned a lot!

**Pull request merged**
