### PR TITLE
chore: bump Python version

### PR DESCRIPTION
**Pull request by agoose77**
This PR introduces `pyupgrade`, bumps the oldest supported Python interpreter from 3.7 to 3.8, and adds support for 3.12 in the metadata.

It also applies a fix for the removal of `NumpyArray.__array__`.

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
Yes, 5.1.0 is a good time for Uproot to drop Python 3.7, though this should merge into the `agoose77/wip-shape-tracking` branch.

Or better yet, a new `main-510` branch should be introduced that `agoose77/wip-shape-tracking` and `agoose77/feat!-bump-python-version` both merge into. This `main-510` will accumulate everything that's going into Uproot 5.1.0 and not anything that will go in later. When 5.1.0 is finally released, `main-510` merges into `main` and disappears. During this transition time, we shouldn't be merging anything big into `main`, either.

I'm in principle in favor of pyupgrade, but if it's going to make a lot of small changes across the codebase, _we should not introduce it_ until after
  * merging of `main-510` into `main`
  * merging of #943 into `main` (that's one big PR that touches a lot of code across the codebase)

**Comment by lobis** [comment]
I guess we should also remove python 3.7 from the GitHub Actions workflow file right?

**Comment by jpivarski** [comment]
> I guess we should also remove python 3.7 from the GitHub Actions workflow file right?

Good point! That would go with this PR. (Go ahead and make the modification directly; we won't merge it until everyone's satisfied with it.)

**Comment by agoose77** [comment]
@lobis that's weird — I thought I had done that here ... I think I'm working on too many PRs at once :laughing: Thanks!

**Comment by lobis** [comment]
Should we also add python 3.12 to the CI? (I tried doing so but found some problems, it's a bit hard to debug with the current status of the pipeline, but I think it should be an easy fix).

**Comment by agoose77** [comment]
> Should we also add python 3.12 to the CI? 

Definitely!

**Comment by agoose77** [comment]
@jpivarski this is ready to merge. It updates our Python min, max versions (>=3.8, <=3.12), and fixes a use of `np.asarray(content)` that is broken by the latest awkward.

**Pull request merged**
