### PR TITLE
feat: Support writing of RNTuple

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by Moelf** [comment]
```python
In [21]: with up.recreate("/tmp/test.root") as file:
    ...:     file.mktree("Events", {"one":"int"})
    ...:     file.mkntuple("ntuple", akform)

In [23]: up.open("/tmp/test.root")["ntuple"]._members
Out[23]: 
{'fCheckSum': 1700499286,
 'fVersion': 0,
 'fSize': 48,
 'fSeekHeader': 866,
 'fNBytesHeader': 133,
 'fLenHeader': 159,
 'fSeekFooter': 1201,
 'fNBytesFooter': 81,
 'fLenFooter': 104,
 'fReserved': 0}

In [22]: rn = up.open("/home/akako/Documents/github/scikit-hep-testdata/src/skhep_testdata/data/test_ntuple_int_10.root")["ntuple"]

In [24]: rn._members
Out[24]: 
{'fCheckSum': 1700499286,
 'fVersion': 0,
 'fSize': 48,
 'fSeekHeader': 866,
 'fNBytesHeader': 133,
 'fLenHeader': 159,
 'fSeekFooter': 1201,
 'fNBytesFooter': 81,
 'fLenFooter': 104,
 'fReserved': 0}
```

**Comment by Moelf** [comment]
in a different file, the `stl_container` test file, we have:
- one header RBlob
- one footer RBlob
- one chunk
```python
In [48]: rn.page_list_envelopes.pagelinklist[0][1].chunk
Out[48]: <Chunk 0-1104>
```
- 30 page data blobs:
```python
In [49]: len(rn.page_list_envelopes.pagelinklist[0])
Out[49]: 30
```

**Comment by Moelf** [comment]
```python
In [227]: with up.recreate("/tmp/test.root") as file:
     ...:     file.mkntuple("ntuple", akform)

In [228]: up.open("/tmp/test.root")["ntuple"].header
Out[228]: MetaData('HeaderReader', env_header={'env_version': 1, 'min_version': 1}, feature_flag=0, rc_tag=1, name='ntuple', ntuple_description='', writer_identifier='uproot 5.0.0rc2', field_records=[MetaData('FieldRecordFrame', field_version=0, type_version=0, parent_field_id=0, struct_role=0, flags=0, field_name='one_integers', type_name='std::int32_t', type_alias='', field_desc='')], column_records=[MetaData('ColumnRecordFrame', type=11, nbits=32, field_id=0, flags=0)], alias_columns=[], extra_type_infos=[], crc32=3689245460)
```

**Comment by Moelf** [comment]
```python
In [444]: with up.recreate("/tmp/test.root") as file:
     ...:     akform =  ak._v2.forms.RecordForm([ak._v2.forms.NumpyForm('float64'), ak._v2.forms.NumpyForm('int32'), ak._v2.forms.Numpy
     ...: Form('bool')], ['one', 'two', 'three'])
     ...:     file.mkntuple("ntuple", akform)
up
In [445]: up.open("/tmp/test.root")["ntuple"].header.field_records
Out[445]: 
[MetaData('FieldRecordFrame', field_version=0, type_version=0, parent_field_id=0, struct_role=0, flags=0, field_name='one', type_name='double', type_alias='', field_desc=''),
 MetaData('FieldRecordFrame', field_version=0, type_version=0, parent_field_id=1, struct_role=0, flags=0, field_name='two', type_name='std::int32_t', type_alias='', field_desc=''),
 MetaData('FieldRecordFrame', field_version=0, type_version=0, parent_field_id=2, struct_role=0, flags=0, field_name='three', type_name='bit', type_alias='', field_desc='')]

In [446]: up.open("/tmp/test.root")["ntuple"].header.column_records
Out[446]: 
[MetaData('ColumnRecordFrame', type=7, nbits=64, field_id=0, flags=0),
 MetaData('ColumnRecordFrame', type=11, nbits=32, field_id=1, flags=0),
 MetaData('ColumnRecordFrame', type=6, nbits=1, field_id=2, flags=0)]
```

**Comment by Moelf** [comment]
working on Footer, turns out it's not empty even if the RNTuple itself is empty:
```python
In [26]: rn = up.open("/home/akako/Documents/github/scikit-hep-testdata/src/skhep_testdata/data/test_ntuple_int_empty.root")["ntuple"]

In [27]: rn.header
Out[27]: MetaData('HeaderReader', env_header={'env_version': 1, 'min_version': 1}, feature_flag=0, rc_tag=1, name='ntuple', ntuple_description='', writer_identifier='ROOT v6.26/06', field_records=[MetaData('FieldRecordFrame', field_version=0, type_version=0, parent_field_id=0, struct_role=0, flags=0, field_name='one_integers', type_name='std::int32_t', type_alias='', field_desc='')], column_records=[MetaData('ColumnRecordFrame', type=11, nbits=32, field_id=0, flags=0)], alias_columns=[], extra_type_infos=[], crc32=4183493504)

# this file is written out by uproot, header is bit-perfect matched
In [28]: up.open("/tmp/test.root")["ntuple"].header
Out[28]: MetaData('HeaderReader', env_header={'env_version': 1, 'min_version': 1}, feature_flag=0, rc_tag=1, name='ntuple', ntuple_description='', writer_identifier='ROOT v6.26/06', field_records=[MetaData('FieldRecordFrame', field_version=0, type_version=0, parent_field_id=0, struct_role=0, flags=0, field_name='one_integers', type_name='std::int32_t', type_alias='', field_desc='')], column_records=[MetaData('ColumnRecordFrame', type=11, nbits=32, field_id=0, flags=0)], alias_columns=[], extra_type_infos=[], crc32=4183493504)

In [29]: rn.footer
Out[29]: MetaData('Footer', env_header={'env_version': 1, 'min_version': 1}, feature_flag=0, header_crc32=4183493504, extension_links=[], col_group_records=[], cluster_summaries=[], cluster_group_records=[MetaData('ClusterGroupRecord', num_clusters=0, page_list_link=MetaData('EnvLink', env_uncomp_size=16, locator=MetaData('Locator', num_bytes=16, offset=1039)))], meta_block_links=[])
```

**Comment by Moelf** [comment]
```python
In [43]: with up.recreate("/tmp/test.root") as file:
    ...:     akform =  ak._v2.forms.RecordForm([ak._v2.forms.NumpyForm('int32')], ['one_integers'])
    ...:     file.mkntuple("ntuple", akform)

In [44]: up.open("/tmp/test.root")["ntuple"].footer
[  1   0   1   0   0   0   0   0   0   0   0   0 128  11  91 249 248 255
 255 255   0   0   0   0 248 255 255 255   0   0   0   0 248 255 255 255
   0   0   0   0 224 255 255 255   1   0   0   0  24   0   0   0   0   0
   0   0  16   0   0   0  16   0   0   0  15   4   0   0   0   0   0   0
 248 255 255 255   0   0   0   0 107 140  67 241]
Out[44]: MetaData('Footer', env_header={'env_version': 1, 'min_version': 1}, feature_flag=0, header_crc32=4183493504, extension_links=[], col_group_records=[], cluster_summaries=[], cluster_group_records=[MetaData('ClusterGroupRecord', num_clusters=0, page_list_link=MetaData('EnvLink', env_uncomp_size=16, locator=MetaData('Locator', num_bytes=16, offset=1039)))], meta_block_links=[])
```

**Comment by Moelf** [comment]
ROOT is happy with the footer for now
```python
In [16]: with up.recreate("/tmp/test.root") as file:
    ...:     akform =  ak._v2.forms.RecordForm([ak._v2.forms.NumpyForm('int32')], ['one_integers'])
    ...:     file.mkntuple("ntuple", akform)

In [17]: ROOT.Experimental.RNTupleReader.Open("ntuple", "/tmp/test.root").PrintInfo()
[ROOT.NTuple] Warning /home/conda/feedstock_root/build_artifacts/root_base_1659775868695/work/root-source/tree/ntuple/v7/src/RNTupleSerialize.cxx:1105 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&):0: RuntimeWarning: Pre-release format version: RC 1
************************************ NTUPLE ************************************
* N-Tuple : ntuple                                                             *
* Entries : 0                                                                  *
********************************************************************************
* Field 1   : one_integers (std::int32_t)                                      *
********************************************************************************
```

**Comment by Moelf** [comment]
```python
In [73]: with up.recreate("/tmp/test.root") as file:
    ...:     akform =  ak._v2.forms.RecordForm([ak._v2.forms.NumpyForm('int32')], ['one_integers
    ...: '])
    ...:     file.mkntuple("ntuple", akform)
    ...:     print(type(file))
    ...:     a = file["ntuple"]
    ...:     print(type(a))
<class 'uproot.writing.writable.WritableDirectory'>
<class 'uproot.writing.writable.WritableNTuple'>
```

**Comment by Moelf** [comment]
```python
In [28]: with up.recreate("/tmp/test.root") as file:
    ...:     akform =  ak._v2.forms.RecordForm([ak._v2.forms.NumpyForm('int32')], ['one_integers
    ...: '])
    ...:     #file.mktree("ntuple", {"a": np.int32})
    ...:     file.mkntuple("ntuple", akform)
    ...:     a = file["ntuple"]
    ...:     a.extend(array)
    ...:     file.close()

In [29]: up.open("/tmp/test.root")["ntuple"].footer
Out[29]: MetaData('Footer', env_header={'env_version': 1, 'min_version': 1}, feature_flag=0, header_crc32=4183493504, extension_links=[], col_group_records=[], cluster_summaries=[MetaData('ClusterSummaryRecord', num_first_entry=0, num_entries=10)], cluster_group_records=[MetaData('ClusterGroupRecord', num_clusters=0, page_list_link=MetaData('EnvLink', env_uncomp_size=16, locator=MetaData('Locator', num_bytes=16, offset=1601)))], meta_block_links=[], crc32=2251102086)
```

**Comment by Moelf** [comment]
reminder that the list of list of list is real:
(file from https://github.com/scikit-hep/uproot5/pull/682)
```python
ref = up.open("/home/akako/Documents/github/scikit-hep-testdata/src/skhep_testdata/data/test_ntuple_large_bit_int64.root")["ntuple"]

In [6]: ref.page_list_envelopes.pagelinklist
Out[6]:
[[InnerListLocator(<Chunk 0-110112>, Cursor(20), num_pages=170),
  InnerListLocator(<Chunk 0-110112>, Cursor(2760), num_pages=1356)],
 [InnerListLocator(<Chunk 0-110112>, Cursor(24484), num_pages=190),
  InnerListLocator(<Chunk 0-110112>, Cursor(27544), num_pages=1523)],
 [InnerListLocator(<Chunk 0-110112>, Cursor(51940), num_pages=190),
  InnerListLocator(<Chunk 0-110112>, Cursor(55000), num_pages=1523)],
 [InnerListLocator(<Chunk 0-110112>, Cursor(79396), num_pages=190),
  InnerListLocator(<Chunk 0-110112>, Cursor(82456), num_pages=1523)],
 [InnerListLocator(<Chunk 0-110112>, Cursor(106852), num_pages=22),
  InnerListLocator(<Chunk 0-110112>, Cursor(107224), num_pages=179)]]
```

**Comment by Moelf** [comment]
for maintainers' sanity, increased the eagerness of some footer reading so you can see the list of list of list structure directly instead of following an indirection via the (fake, i.e. no in RNTuple spec) `InnerListLocator):
```python
In [157]: ref = up.open("/home/akako/Documents/github/scikit-hep-testdata/src/skhep_testdata/data/test_n
     ...: tuple_int_10.root")["ntuple"]
ref.page
In [158]: ref.page_list_envelopes
Out[158]: MetaData('PageLink', env_header={'env_version': 1, 'min_version': 1}, pagelinklist=[[[MetaData('PageDescription', num_elements=10, locator=MetaData('Locator', num_bytes=40, offset=1033))]]], crc32=2120950660)

In [159]: ref.page_list_envelopes.pagelinklist
Out[159]: [[[MetaData('PageDescription', num_elements=10, locator=MetaData('Locator', num_bytes=40, offset=1033))]]]
```

**Comment by Moelf** [comment]
```python
In [149]: array
Out[149]: <Array [{one_integers: 9}, {...}, ..., {...}] type='10 * {one_integers: int32}'>

In [150]: with up.recreate("/tmp/test.root") as file:
     ...:     akform =  ak._v2.forms.RecordForm([ak._v2.forms.NumpyForm('int32')], ['one_integers'])
     ...:     #file.mktree("ntuple", {"a": np.int32})
     ...:     file.mkntuple("ntuple", akform)
     ...:     a = file["ntuple"]
     ...:     a.extend(array)
     ...:     file.close()
     ...:     rn = up.open("/tmp/test.root")["ntuple"]
     ...:     assert ak.all(rn.arrays()["one_integers"]  == np.array([9,8,7,6,5,4,3,2,1,0]))
```

**Comment by jpivarski** [comment]
@Moelf, I'm marking this PR as "inactive." When the RNTuple-writing feature is eventually implemented, it might need to be overlaid on a more recent version of `main` (that is, by closing this and reopening it as a new PR), but I'd like this to remain in the list of PRs as a reminder to get back to it and a knowledge base of how to do it.

**Comment by Moelf** [comment]
looks like we can still update?

**Comment by jpivarski** [comment]
Got it, thanks! We might be doing a lot of bug-fixes in the coming weeks when a wave of non-early-adopter users get Uproot 5. It shouldn't impact the RNTuple submodule, but `main` will move.

**Comment by jpivarski** [comment]
`awkward._v2` is now just `awkward`. We couldn't find a clean way to make a fake submodule point at its parent. (You'd think you could, but there were hidden subtleties.) That's the reason for the first failure. The `main` branch takes care of that for most of the codebase, but if you have new code in this PR branch that assumes the existence of a `_v2` submodule, you should be able to fix it by just removing that "`._v2`" string.

**Review by jpivarski — APPROVED** [review]
I'm in favor of merging this PR as soon as the tests pass.

  * It includes important code for _reading_ `std::array<T>`. We want to get all of the reading updates in.
  * We don't want the code for writing to get out of date with `main`, even if it is incomplete, so that it will be easier to finish later.
  * None of this should break things for regular Uproot users, since they'd have to go out of their way to even try to use this. At the very least, they'd have to get access to a file with an RNTuple in it, and those are well-advertised as being experimental.

**Comment by Moelf** [comment]
seems weird
```
tests/test_0791-protect-uproot-project_columns-from-dask-node-names.py::test - AssertionError: assert 
```

only happens on >3.7

**Comment by jpivarski** [comment]
dask-awkward only runs in Python 3.7+. However, it shouldn't fail. I'm going to run the tests in `main`: https://github.com/scikit-hep/uproot5/actions/runs/3851990477

We'll see if it's broken overall or only in this branch.

**Comment by Moelf** [comment]
looks like manually triggered CI also failed on `main`

**Pull request merged**
