### PR TITLE
chore: update Uproot to require Awkward 2.0.0rc1.

### PR DESCRIPTION
**Pull request by jpivarski**
This PR won't pass tests until Awkward 2.0.0rc1 is actually released on PyPI.

### CODE REVIEW

**Comment by jpivarski** [comment]
Thanks for checking that. We can do that as a first test, but eventually we'll want a post-2.0.0rc1 awkward-dask release. (This is all a big chicken-and-egg problem.)

**Comment by douglasdavis** [comment]
dask-awkward `2022.10a0` is now on PyPI 👍

**Comment by jpivarski** [comment]
Yes, I completely forgot that I had already done it.

I just scanned over the two diffs, and they (the diff of diffs) are essentially the same—that is, I understand the differences. Not wrapping `ForthMachine64.output` in `np.asarray` is a little better (this PR), and this PR also doesn't have the hack of pulling in Awkward from `main`, unnecessary since yesterday. Also, the diff in this PR is fresher; it's on top of other improvements that have gone into Uproot in the past 26 days, so I closed the old one.

**Comment by jpivarski** [comment]
This last triggering of the tests is a sanity check: the test of be23aec13d3134db67cfef3d6570275c58845cfd (which was successful) should have been enough. I just want to see it go from start to finish.

Other than that, I think it's done. If you (@agoose77) give the approval, I'll merge it and that unblocks Coffea tests.

**Pull request merged**
