### PR TITLE
feat: Implement read coalescing algorithm

### PR DESCRIPTION
**Pull request by nsmith-**
Tuning to be investigated

### CODE REVIEW

**Comment by nsmith-** [comment]
The removal of the stateful handle is motivated by https://github.com/scikit-hep/uproot5/issues/1157#issuecomment-1981832282

**Comment by nsmith-** [comment]
Only in python 3.11+ do we see
```
E               ValueError: not a ROOT file: first four bytes are b'\xec_wu'
E               in file s3://pivarski-princeton/pythia_ppZee_run17emb.picoDst.root
```
looking into it...

**Comment by nsmith-** [comment]
The problem is the signature of `fs.cat_file`. For the file
```python
import fsspec

fs, path = fsspec.url_to_fs("s3://pivarski-princeton/pythia_ppZee_run17emb.picoDst.root", anon=True)
```

If I create a file-object handle and read the first 4 bytes, I get:
```python
fh = fs.open(path)
fh.seek(0)
assert fh.read(4) == b"root"
```

if I instead use `cat_file`, I find:
```python
data = fs.cat_file(path, 0, 4)
assert len(data) == 4  # fails, len(data) is 978299156
assert data == b"root" # also fails, data[:4] is b'\x00\x00\xf1l'
```

So there is some mismatch in the behavior that I was initially puzzled by. Then I realized that, depending on the implementation, `fs.cat_file` can have different signatures and the s3fs one has a different order of keyword arguments. I made a UX issue in https://github.com/fsspec/filesystem_spec/issues/1600 and used keywords here.

**Review by jpivarski — APPROVED** [review]
As I understand it, src/uproot/source/coalesce.py is a suite of utility functions used only by FSSpecSource to merge nearby but not necessarily adjacent byte requests—download a bit too much data, but have (far?) fewer requests and responses in flight, which is a net savings, depending on how a network's throughput and latency compare.

Presumably, it would need to be tuned for each network. How are the default settings? (It looks to me like the coalesce functions are always used by FSSpecSource, so this will affect the default case.) The most conservative default is to only coalesce adjacent byte ranges, but the most common network scenario (grad student in a basement, trying to get data from CERN) is more latency-bound than throughput-bound. Maybe the default could accept 25% over-read or so.

I see that this also only affects FSSpecSource. It could, in principle, be applied to the pre-FSSpecSources, but there's less reason to do that. FSSpecSource has the many-requests-in-flight model built into it, and the old sources attempt to do vector reads (only one request in flight).

I'm in favor of this. If @lobis is available, it would be great to hear what you think! If we don't hear from you by Thursday, I think we should go ahead with this PR.

**Comment by nsmith-** [comment]
The defaults are in spirit similar to the CMSSW defaults, though the use case is certainly different. I was hoping to gain some experience in the wild how different these are.

As for implementing it in pre-fsspec sources, indeed that is an option, and one I think may be useful. For example, even in the case of vector reads (which fsspec is now doing if the protocol supports, through the `cat_ranges` interface) there may be value in issuing separate reasonably-sized vector read requests rather than one large one.

**Comment by jpivarski** [comment]
It's Thursday; I think we should go ahead with this PR. I'll update to `main` and then merge.

**Pull request merged**
