### PR TITLE
docs: add a CITATION.cff for Uproot.

### PR DESCRIPTION
**Pull request by jpivarski**
Hi @jpivarski, @henryiii, @agoose77, @reikdas, @kkothari2001, @aryan26roy, @Moelf, @nsmith-, @chrisburr, @kratsg!

I made this author list for Uproot by scanning through _all_ the Uproot 1-3 and Uproot 4-5 contributions and identifying those of you who have made major contributions. It's hard to put a cut-off on "major" and I definitely appreciate all of the community contributions. I think a good way to recognize them both is with a CITATION.cff _and_ an .all-contributorsrc.

Take a look at your entry in the CITATIONS.cff file and let me know if something should be changed: email, institution, name/spelling, and @kkothari2001 and @aryan26roy, let me know if you have or get an ORCID (https://orcid.org).

If you think I've missed someone, I can consider adding one or two more names to the author list. Below are the notes that I took while scanning through all the contributions.

### Uproot 1-3:

- `plexoos`: devops and some interpretations (Double32)
- `matthewfeickert`: devops
- `tamasgal`: interpretations
- `kreczko`: provenance
- `oshadura`: ZSTD compression
- `nbiederbeck`: HTTP authentication
- `masonproffitt`: classname function and interpretation (long long)
- `benkrikler`: entry numbering when iterating over Pandas
- `guitargeek`: aligned Pandas output
- `bfis`: File.update
- `ast0815`: skip missing TTrees in iterate
- `jrueb`: lax conformance between files
- `HealthyPear`: file reporting in uproot.iterate

### Uproot 4-5:

- `veprbl`: devops, TDatime, TTable[^1]
- `nikoladze`: XRootD bug-fixes[^1]
- `jrueb`: WritableFile improvements
- `ryuwd`: XRootD bug-fixes/work-arounds
- `douglasdavis`: TArrayD.reshape
- `kakwok`: ReadOnlyDirectory initialization bug
- `pfackeldey`: memmap streamlining
- `mpad`: AsDtypeInPlace
- `btovar`: exception-handling for multithreaded
- `duncanmmacleod`: devops (test suite in source dist)
- `klieret`: docs[^1]
- `dcervenkov`: XRootD version string handling[^1]
- `beojan`: TGraph, RooCurve, RooHist behaviors[^1]
- `cozzyd`: HTTP authentication
- `HealthyPear`: TProfile reading bug
- `tamasgal`: fix lazy
- `andrzejnovak`: Damerau-Levenshtein distance for KeyNotFound reporting
- `raymondEhlers`: histogram axis swap
- `bendavid`: faster jagged header bytes removal

[^1]: needs all-contributors

### CODE REVIEW

**Comment by jpivarski** [comment]
Issue #727 and its associated PRs has added all of the people indicated above to all-contributors.

**Comment by jpivarski** [comment]
Let me know by 15:00 Geneva-time tomorrow (Friday) if anyone has any objections, otherwise, I'll merge it at that time.

**Comment by aryan26roy** [comment]
Hey @jpivarski, my ORCID ID is this: https://orcid.org/0000-0001-5220-8725

**Comment by kkothari2001** [comment]
Here's my ORCHID: https://orcid.org/0000-0001-8593-722X

**Comment by jpivarski** [comment]
Looks like everything is done. Thanks, everyone!

**Comment by jpivarski** [comment]
Here's the "cite this repository" drop-down on the top-right of the GitHub homepage:

image

And this is what Zenodo looks like when you follow the DOI link (i.e. the [DOI 10.5281/zenodo.4340632](https://doi.org/10.5281/zenodo.4340632) badge):

image

**Pull request merged**
