### PR TITLE
build: change build to autogen version info

### PR DESCRIPTION
**Pull request by lgray**
This may help in streamlining releases in the future, but it's up to opinion on operations.
It also makes it easier for users to see if they are using a build installed from source.

@jpivarski @lobis

### CODE REVIEW

**Comment by lgray** [comment]
@jpivarski some of these failures seem ~persistent but are obviously not related. 

Anyway - this one isn't super high priority. Decided to propose the option to y'all!

**Review by jpivarski — APPROVED** [review]
I had been avoiding this on principle, but I can no longer remember the reason why. Since I can't remember it, I guess it's time to give in and let hatch-vcs manage the version.py.

We should merge this _after_ the 5.2.0 release.

Thanks!

**Comment by lgray** [comment]
@jpivarski reminder of this one, but again low priority.

**Comment by jpivarski** [comment]
Yeah, I know. Okay, I'll try it out now.

**Comment by jpivarski** [comment]
It worked, and I don't see any reason to not use hatch-vcs. Awkward Array uses hatchling as well, though its release process is more complex because there's an awkward-cpp part that absolutely must be versioned by hand. (Its version number is essentially an ABI between the two parts of the project, so we want to control that.)

**Pull request merged**
