### PR TITLE
chore: dask_awkward.test_utils moved in ContinuumIO/dask-awkward#76

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by jpivarski** [comment]
FYI, @douglasdavis: `assert_eq` has a hidden dependency on `pyarrow`. Did you intend to make `dask_awkward` strictly depend on `pyarrow`?

```
tests/test_0700-dask-empty-arrays.py:11: in <module>
    from dask_awkward.lib.testutils import assert_eq
../../../miniconda3/envs/test/lib/python3.8/site-packages/dask_awkward/lib/__init__.py:16: in <module>
    from dask_awkward.lib.io.parquet import from_parquet, to_parquet
../../../miniconda3/envs/test/lib/python3.8/site-packages/dask_awkward/lib/io/parquet.py:7: in <module>
    import pyarrow.parquet as pq
E   ModuleNotFoundError: No module named 'pyarrow'
```

**Comment by jpivarski** [comment]
If the tests pass, @agoose77 or @Moelf, you can approve this PR, merge it into `main`, and then use it to fix the tests in your PRs: #713 and #705.

When running locally,

```bash
pip install -U dask-awkward
```

(or maybe you're using a tool that automatically pulls the latest dependencies into your venv, in which case, good for you!)

**Comment by agoose77** [comment]
I've added the LB constaint to `pyproject.toml`, and also removed the manual install of `dask-awkward` from the CI (it's installed later in the job by the dev dependencies).

**Comment by jpivarski** [comment]
Oh, if it was not in pyproject.toml, then I was probably wrong about dask-awkward not declaring its dependencies. Sorry for the confusion, @douglasdavis!

**Comment by agoose77** [comment]
The only change I made was to add `>= VERSION` to the `dask-awkward` dependency for uproot5, so that we explicitly don't request a version before they made this change.

**Comment by jpivarski** [comment]
Okay, I'm going to merge this because several PRs need it.

**Pull request merged**
